# Generated by Django 3.1.3 on 2020-12-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FilePathField(default=1, path='img'),
            preserve_default=False,
        ),
    ]
