# Generated by Django 3.1.3 on 2020-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(null=True, path='C:/Users/ACER/Desktop/py/portfolio/projects/static/img'),
        ),
    ]
